name: Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 1
    - name: Download and extract test data 
      env:
          GITHUB_WORKSPACE: ${{github.workspace}}
      run: |
        sh downloadTestData.sh
        mkdir /github/workspace/Test/testData
        cp ${{github.workspace}}/Test/testData/* /github/workspace/Test/testData
        ls /github/workspace/Test/testData
    - uses: joergbrech/moxunit-action@master
      with:
        src: src external
        tests: Test
        with_coverage: true
        cover_xml_file: coverage.xml
    - uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
